name: ios-react-native-metrics-sdk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-xcode-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: NPM install
      run: npm install
      working-directory: BuildProject
    - name: Echo
      run: echo ${IOS_REPO_ACCESS_TOKEN}
      working-directory: BuildProject/ios
      env: 
        IOS_REPO_ACCESS_TOKEN: ${{ secrets.IOS_REPO_ACCESS_TOKEN }}
    - name: Cocoapod install
      run: pod install
      working-directory: BuildProject/ios
      env: 
        IOS_REPO_ACCESS_TOKEN: ${{ secrets.IOS_REPO_ACCESS_TOKEN }}
    - name: Build
      run: xcodebuild -workspace BuildProject.xcworkspace -configuration Debug -scheme BuildProject -destination 'platform=iOS Simulator,name=iPhone 11'
      working-directory: BuildProject/ios
  build-and-test-xcode-11:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: sinoru/actions-setup-xcode@v1.1.2
      with:
        xcode-version: '11.7'
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: NPM install
      run: npm install
      working-directory: BuildProject
    - name: Cocoapod install
      run: pod install
      working-directory: BuildProject/ios
    - name: Build
      run: xcodebuild -workspace BuildProject.xcworkspace -configuration Debug -scheme BuildProject -destination 'platform=iOS Simulator,name=iPhone 11'
      working-directory: BuildProject/ios
